### ISSUE TITLE
[Bug] Font Inconsistency in Firefox

### ISSUE THREAD

**Issue by itsadithyav** [mcspidey95/TerminalTab#1]
![image](https://github.com/user-attachments/assets/4d52dbf2-3b30-4c88-879c-178a90431219)
The font in the drop down menu doesn't follow the font used by the home page.

Firefox Version - 128.0.3 (64 Bit)
Windows 11 Version - 10.0.22631 Build 22631

**Comment by mcspidey95** [comment]
ask firefox to hire me, ill fix it 👍
