### ISSUE TITLE
[Bug] Ctrl+A selects the entire homepage instead of search bar text

### ISSUE THREAD

**Issue by itsadithyav** [mcspidey95/TerminalTab#3]
![image](https://github.com/user-attachments/assets/ca15466c-6445-4ebd-aa9f-da598231718a)

Ctrl+A selects the entire homepage instead of search bar text and also types a in the search box

Firefox Version - 128.0.3 (64 Bit)
Windows 11 Version - 10.0.22631 Build 22631

**Comment by mcspidey95** [comment]
Cheers 👍
