### ISSUE TITLE
[Bug] When Ctrl, Func, Alt and Windows keys are pressed disable typing

### ISSUE THREAD

**Issue by itsadithyav** [mcspidey95/TerminalTab#4]
Ctrl + c/v, Windows + v, and other similar keys won't work cause it types the keys in the searchbox instead

**Comment by mcspidey95** [comment]
I've disabled typing when Ctrl, Alt and windows key is pressed. fn key doesn't give any code, so it isn't detected. So you'll have to live with that.

Cheers 👍
