### ISSUE TITLE
[Bug] 2 Bugs found

### ISSUE THREAD

**Issue by itsadithyav** [mcspidey95/TerminalTab#8]
1. Pressing Ctrl+V doesn't paste the text over and over again. It instead replaces the existing text.
https://github.com/user-attachments/assets/33b82c81-9019-4017-8299-08d722e1ab70
3. Highlighted text doesn't get UN-highlighted upon click on the search bar or pressing any other keys.
![image](https://github.com/user-attachments/assets/6c28ed46-ee01-4eb0-865e-85a3fc544f05)

Browser Used - Firefox
Windows 11 Home Version	10.0.22631 Build 22631

**Comment by mcspidey95** [comment]
The first one was a very tiny + missing :)

2nd one is already fixed. I would recommend you to either switch browsers or else forward my resume to firefox.

Cheers 👍
